def print_yangtuo():

	print('┆     　┏┓　　┏┓             ┆')
	print('┆      ┏┛┻━━━┛  ┻┓           ┆')
	print('┆     ┃　　　　   ┃          ┆')
	print('┆    ┃　 　 ━　    ┃         ┆')
	print('┆    ┃  ┳┛ 　┗┳　  ┃         ┆')
	print('┆    ┃　　　　　   ┃         ┆')
	print('┆     ┃　　┻　    ┃          ┆')
	print('┆     ┗━┓　马  ┏━┛           ┆')
	print('┆  　  　┃　勒 ┃             ┆')
	print('┆  　  　┃　 戈　┗━━━━━┓     ┆')
	print('┆   　  ┃　壁　　　　 　┣┓   ┆')
	print('┆   　　┃　 的 羊 驼 　┏┛    ┆')
	print('┆   　 　┗┓ ┓┏━┳┓ ━┳ ┏┛      ┆')
	print('┆   　 　　 ┃┫┫　  ┃┫┫       ┆')
	print('┆   　 　　 ┗┻┛　  ┗┻┛       ┆')
	print('┆    神兽镇楼   工程不挂     ┆')
	print('泥马说:')
	print('        羊驼的聪明难以想象 ')
	print('       ')
	print('小小编程写字间 ，马勒戈壁大草原')
	print('')
	print('老板紧督写工程 ，客户又让改文件')
	print('')
	print('要问心中多少愁 ？万千羊驼在奔腾')
	print('')
	print('日月交替再明天 ，年岁回首无情钱')
	print('')
	print('')
print_yangtuo()
